name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      build-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.AUTH_TOKEN}}

          - name: 'Build & Push Docker Image'
            run: |
              docker build . --tag ghcr.io/lapoelisacci/k-deploy:latest
              docker push ghcr.io/lapoelisacci/k-deploy:latest
