name: build 
on: [push]
jobs:
build-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the Docker image
run: |
       docker build . --tag ghcr.io/LapoElisacci/k-deploy:latest
       docker run ghcr.io/LapoElisacci/k-deploy:latest
       docker push ghcr.io/LapoElisacci/k-deploy:latest
